# Generated by Django 3.0.7 on 2020-06-15 17:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0004_auto_20200614_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='commentors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default='blank', max_length=300), default=[], size=None),
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default='blank', max_length=300), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(max_length=30),
        ),
    ]
