# Generated by Django 3.0.7 on 2020-06-15 17:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0005_auto_20200615_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='commentors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default='blank', max_length=300), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default='blank', max_length=300), default=list, size=None),
        ),
    ]
