# Generated by Django 3.0.7 on 2020-06-15 17:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0006_auto_20200615_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='commentors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default='blank', max_length=300), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default='blank', max_length=300), blank=True, default=list, null=True, size=None),
        ),
    ]
