# Generated by Django 3.0.7 on 2020-06-15 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0007_auto_20200615_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='commentors',
        ),
    ]
