# Generated by Django 3.0.7 on 2020-06-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0011_auto_20200620_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.TextField(default='blank', max_length=300),
        ),
    ]
